-- Step 1: Add dual-language support columns
ALTER TABLE public.resources
  ADD COLUMN IF NOT EXISTS alt_url TEXT,
  ADD COLUMN IF NOT EXISTS alt_source TEXT;

-- Step 2: Delete all old C++ resources
DELETE FROM public.resources WHERE domain = 'cpp-programming';

-- Step 3: Insert new Dual-Language C++ resources
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ Tutorial for Beginners (Full Course)', 'https://www.youtube.com/watch?v=vLnPwxZdW4Y', 'Bro Code — Complete C++ beginner tutorial in one video', 'video', 1, 1, 'https://www.youtube.com/watch?v=yGB9jhsEsr8', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Introduction to C++', 'https://www.learncpp.com/cpp-tutorial/introduction-to-cplusplus/', 'What is C++, history, and why learn it', 'article', 1, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Setting Up Your IDE', 'https://www.learncpp.com/cpp-tutorial/introduction-to-the-compiler-linker-and-libraries/', 'Compiler, linker, and IDE setup guide', 'article', 1, 3, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Variables & Data Types', 'https://www.youtube.com/watch?v=qEgCT87KOfc', 'The Cherno — Variables and data types in C++', 'video', 1, 4, 'https://www.youtube.com/watch?v=jigb6W35zHc', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Input & Output (cin/cout)', 'https://www.learncpp.com/cpp-tutorial/introduction-to-iostream-cout-cin-and-endl/', 'Using iostream for user input and output', 'article', 1, 5, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Operators in C++', 'https://www.youtube.com/watch?v=cZc-bSCSliU', 'Caleb Curry — Operators and expressions in C++', 'video', 2, 1, 'https://www.youtube.com/watch?v=7D5A5ZMKRWw', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'If-else & Switch Statements', 'https://www.learncpp.com/cpp-tutorial/if-statements-and-blocks/', 'Conditional control flow with if-else and switch', 'article', 2, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Loops in C++ (for, while, do-while)', 'https://www.learncpp.com/cpp-tutorial/for-statements/', 'All loop types explained with examples', 'article', 2, 3, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Break, Continue & Scope', 'https://www.learncpp.com/cpp-tutorial/break-and-continue/', 'Loop control statements and variable scope', 'article', 2, 4, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Type Conversion & Casting', 'https://www.learncpp.com/cpp-tutorial/implicit-type-conversion-coercion/', 'Implicit and explicit type conversions in C++', 'article', 2, 5, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Bitwise Operators', 'https://www.learncpp.com/cpp-tutorial/bitwise-operators/', 'AND, OR, XOR, NOT, shift operators explained', 'article', 2, 6, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Pointers in C++', 'https://www.youtube.com/watch?v=DTxHyVn0ODg', 'The Cherno — Understanding pointers clearly', 'video', 3, 1, 'https://www.youtube.com/watch?v=EvYmTCx9BFs', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'References in C++', 'https://www.youtube.com/watch?v=IzoFn3dfsPA', 'The Cherno — References vs pointers', 'video', 3, 2, 'https://www.youtube.com/watch?v=a7Wim2t053E', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Arrays in C++', 'https://www.youtube.com/watch?v=ENDaJi08jCU', 'The Cherno — Static and dynamic arrays', 'video', 3, 3, 'https://www.youtube.com/watch?v=ePJxpxsnkGw', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Strings in C++', 'https://www.youtube.com/watch?v=ijIxcB9qjaU', 'The Cherno — C-style strings vs std::string', 'video', 3, 4, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Structs in C++', 'https://www.learncpp.com/cpp-tutorial/introduction-to-structs-members-and-member-selection/', 'User-defined data types with structs', 'article', 3, 5, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Enums in C++', 'https://www.youtube.com/watch?v=x55jfOd5PEE', 'The Cherno — Enumerations and scoped enums', 'video', 3, 6, 'https://www.youtube.com/watch?v=jCfR7CFlzts', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Functions in C++', 'https://www.youtube.com/watch?v=V9zuox47zr0', 'The Cherno — Function declaration, definition, and calling', 'video', 4, 1, 'https://www.youtube.com/watch?v=RFLFX1boGwo', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Function Parameters (Pass by Value/Reference)', 'https://www.learncpp.com/cpp-tutorial/passing-arguments-by-value/', 'Pass by value, reference, and pointer', 'article', 4, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Default Arguments & Overloading', 'https://www.learncpp.com/cpp-tutorial/default-arguments/', 'Default parameters and function overloading', 'article', 4, 3, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Recursion', 'https://www.youtube.com/watch?v=ke0zy5-K6RY', 'Reducible — Recursion explained visually', 'video', 4, 4, 'https://www.youtube.com/watch?v=JRKs3s15Kjc', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Header Files & Multi-file Projects', 'https://www.youtube.com/watch?v=9RJTQmK0YPI', 'The Cherno — Header files, include guards, and linking', 'video', 4, 5, 'https://www.youtube.com/watch?v=7D5A5ZMKRWw', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Basic Problems', 'https://www.geeksforgeeks.org/cpp-programming-examples/', 'GFG — Even/Odd, Sum of Digits, Reverse Number', 'exercise', 5, 1, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Logic Building', 'https://www.hackerrank.com/domains/cpp', 'HackerRank — C++ domain problems', 'exercise', 5, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Arrays & Strings', 'https://leetcode.com/problemset/?topicSlugs=array,string', 'LeetCode — Array and string problems', 'exercise', 5, 3, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ Exercises (W3Schools)', 'https://www.w3schools.com/cpp/cpp_exercises.asp', 'W3Schools — Interactive C++ exercises by topic', 'exercise', 5, 4, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Classes & Objects', 'https://www.youtube.com/watch?v=2BP8NhxjrO0', 'The Cherno — Classes in C++', 'video', 6, 1, 'https://www.youtube.com/watch?v=nGJTWaaFdjc', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Classes vs Structs', 'https://www.youtube.com/watch?v=fLgTtaqqJp0', 'The Cherno — When to use class vs struct', 'video', 6, 2, 'https://www.youtube.com/watch?v=tL8vnfFFzVQ', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Constructors & Destructors', 'https://www.youtube.com/watch?v=FXhALMsHwEY', 'The Cherno — Constructor types and destructor', 'video', 6, 3, 'https://www.youtube.com/watch?v=EEJUPXFKe8Q', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Encapsulation & Access Specifiers', 'https://www.geeksforgeeks.org/cpp/encapsulation-in-cpp/', 'Public, private, protected access modifiers and encapsulation', 'article', 6, 4, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Static Members & Methods', 'https://www.youtube.com/watch?v=V-BFlMrBtqQ', 'The Cherno — Static keyword in classes', 'video', 6, 5, 'https://www.youtube.com/watch?v=QcLI2zGVYFo', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'The ''this'' Pointer', 'https://www.learncpp.com/cpp-tutorial/the-hidden-this-pointer-and-member-function-chaining/', 'The implicit this pointer and its uses', 'article', 6, 6, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Const in Classes', 'https://www.youtube.com/watch?v=4fJBrditnJU', 'The Cherno — Const correctness with classes', 'video', 6, 7, 'https://www.youtube.com/watch?v=i3a-G6Ebh9E', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Copy Constructor & Copy Assignment', 'https://www.learncpp.com/cpp-tutorial/the-copy-constructor/', 'Deep copy vs shallow copy, Rule of Three', 'article', 7, 1, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Operator Overloading', 'https://www.youtube.com/watch?v=mS9755gF66w', 'The Cherno — Overloading operators in C++', 'video', 7, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Dynamic Memory (new/delete)', 'https://www.youtube.com/watch?v=sNcj0lPxFfc', 'The Cherno — Heap allocation with new and delete', 'video', 7, 3, 'https://www.youtube.com/watch?v=2Y0b9nFA9s8', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Smart Pointers', 'https://www.youtube.com/watch?v=UOB7-B2MfwA', 'The Cherno — unique_ptr, shared_ptr, weak_ptr', 'video', 7, 4, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Move Semantics & Rvalue References', 'https://www.youtube.com/watch?v=ehMg6zvXuMY', 'The Cherno — Move semantics explained', 'video', 7, 5, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Shallow vs Deep Copy', 'https://www.geeksforgeeks.org/shallow-copy-and-deep-copy-in-c/', 'GFG — Difference between shallow and deep copy', 'article', 7, 6, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Inheritance', 'https://www.youtube.com/watch?v=X8nYM8wdNRE', 'The Cherno — Inheritance in C++', 'video', 8, 1, 'https://www.youtube.com/watch?v=RO1ZYW9NAzg', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Types of Inheritance', 'https://www.learncpp.com/cpp-tutorial/introduction-to-inheritance/', 'Single, multiple, multilevel inheritance', 'article', 8, 2, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Virtual Functions', 'https://www.youtube.com/watch?v=oIV2KchSyGQ', 'The Cherno — Virtual functions & vtables', 'video', 8, 3, 'https://www.youtube.com/watch?v=fB3JHNnlRfI', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Pure Virtual Functions (Interfaces)', 'https://www.youtube.com/watch?v=UWAdd13EfM8', 'The Cherno — Abstract classes and interfaces', 'video', 8, 4, 'https://www.youtube.com/watch?v=RBAWWutf0fY', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Virtual Destructors', 'https://www.youtube.com/watch?v=jELbKhGkEi0', 'The Cherno — Why virtual destructors matter', 'video', 8, 5, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Multiple Inheritance & Diamond Problem', 'https://www.learncpp.com/cpp-tutorial/virtual-base-classes/', 'Virtual base classes and the diamond problem', 'article', 8, 6, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Casting in C++ (static, dynamic, const, reinterpret)', 'https://www.youtube.com/watch?v=pWZS1MtxI-A', 'The Cherno — All four C++ casts explained', 'video', 8, 7, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'OOP Practice Problems', 'https://www.geeksforgeeks.org/cpp-polymorphism/', 'GFG — Practice polymorphism and inheritance', 'exercise', 8, 8, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Templates in C++', 'https://www.youtube.com/watch?v=I-hZkUa9mIs', 'The Cherno — Function and class templates', 'video', 9, 1, 'https://www.youtube.com/watch?v=kKJeekDKU30', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Introduction to STL', 'https://www.geeksforgeeks.org/the-c-standard-template-library-stl/', 'GFG — Overview of Standard Template Library', 'article', 9, 2, 'https://www.youtube.com/watch?v=c9iREsYpayk', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Containers in STL', 'https://www.geeksforgeeks.org/containers-cpp-stl/', 'GFG — Different types of containers in C++', 'article', 9, 3, 'https://www.youtube.com/watch?v=m0gnToak2-g', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'std::vector', 'https://www.youtube.com/watch?v=PocJ5jXv8No', 'The Cherno — Using vectors properly', 'video', 9, 4, 'https://www.youtube.com/watch?v=wKDvMcJiEPM', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'std::list', 'https://www.geeksforgeeks.org/list-cpp-stl/', 'GFG — Doubly linked list in STL', 'article', 9, 5, 'https://www.youtube.com/watch?v=OI4CXwpMBhE', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'std::map & std::unordered_map', 'https://www.geeksforgeeks.org/map-cpp-stl/', 'Key-value containers: map, unordered_map', 'article', 9, 6, 'https://www.youtube.com/watch?v=KwS-Vbsha1k', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Iterators', 'https://www.learncpp.com/cpp-tutorial/introduction-to-iterators/', 'Iterator types and how to traverse containers', 'article', 9, 7, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Function Objects (Functors)', 'https://www.geeksforgeeks.org/functors-in-cpp/', 'GFG — Using objects as functions', 'article', 9, 8, 'https://www.youtube.com/watch?v=g4AQiptpcI8', 'CodeWithHarry');
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'Lambda Functions', 'https://www.youtube.com/watch?v=mWgmBBz0y8c', 'The Cherno — Lambda expressions in C++', 'video', 9, 9, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'STL Algorithms (sort, find, accumulate)', 'https://www.learncpp.com/cpp-tutorial/introduction-to-standard-library-algorithms/', 'Common STL algorithms and how to use them', 'article', 9, 10, NULL, NULL);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week, alt_url, alt_source) VALUES ('cpp-programming', 'cpp-programming', 'C++ STL Cheat Sheet', 'https://www.geeksforgeeks.org/cpp-stl-cheat-sheet/', 'GFG — Quick reference for all STL containers and algorithms', 'docs', 9, 11, NULL, NULL);
