-- Fix C++ Playlist Links & Broken Links

UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=6' WHERE title = 'Header Files & Operators' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=7' WHERE title = 'Reference Variables & Typecasting' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=8' WHERE title = 'Constants & Operator Precedence' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=9' WHERE title = 'If-else & Switch Case' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=10' WHERE title = 'Loops (for, while, do-while)' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=11' WHERE title = 'Break & Continue' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=12' WHERE title = 'Pointers In C++' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=13' WHERE title = 'Arrays & Pointer Arithmetic' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=14' WHERE title = 'Struct, Union & Enum' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=15' WHERE title = 'Function Prototype & Functions' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=16' WHERE title = 'Call By Value & Call By Reference' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=17' WHERE title = 'Inline Functions & Default Parameters' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=18' WHERE title = 'Recursion & Recursive Functions' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=19' WHERE title = 'Function Overloading' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=20' WHERE title = 'OOP in C++' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=21' WHERE title = 'Classes & Access Modifiers' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=22' WHERE title = 'Nesting Of Member Functions' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=23' WHERE title = 'Objects In C++' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=24' WHERE title = 'Static Data Members & Methods' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=25' WHERE title = 'Array Of Objects & Object As Parameter' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=29' WHERE title = 'Constructors In C++' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=30' WHERE title = 'Parameterized & Default Constructor' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=31' WHERE title = 'Constructor Overloading' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=33' WHERE title = 'Dynamic Initialisation Of Objects' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=34' WHERE title = 'Copy Constructor' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=35' WHERE title = 'Destructor' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=36' WHERE title = 'Inheritance Part 1' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=37' WHERE title = 'Inheritance Part 2' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=38' WHERE title = 'Single Inheritance' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=39' WHERE title = 'Use Of Protected Access Modifier' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=40' WHERE title = 'Multi-Level Inheritance Part 1' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=41' WHERE title = 'Multi-Level Inheritance Part 2' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=44' WHERE title = 'Virtual Base Class Part 1' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=45' WHERE title = 'Virtual Base Class Part 2' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=46' WHERE title = 'Constructor In Derived Class Part 1' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=47' WHERE title = 'Constructor In Derived Class Part 2' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=48' WHERE title = 'Initialisation List in Constructors' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=50' WHERE title = '"new" & "delete" Keywords' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=51' WHERE title = 'Pointers to Objects' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?list=PLu0W_9lII9agpFUAlPFe_VNSlXW5uE0YL&index=54' WHERE title = 'Polymorphism' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?v=zJOMt5f1KjI&list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ&index=9' WHERE title = 'Bitwise Operator & Data Type Modifiers' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.youtube.com/watch?v=Wdjr6uoZ0e0&list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA&index=22' WHERE title = 'Strings In C++ (up to 30:04)' AND domain = 'cpp-programming';
UPDATE public.resources SET url = 'https://www.geeksforgeeks.org/cpp-programming-examples/' WHERE title LIKE 'Practice:%' AND domain = 'cpp-programming';
