-- Fix: Replace all C++ resources with English-only content
-- Run this in the Supabase SQL Editor

-- Step 1: Delete all old C++ resources
DELETE FROM public.resources WHERE domain = 'cpp-programming';

-- Step 2: Insert new English-only C++ resources
-- Week 1: Introduction & Basics
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ Tutorial for Beginners (Full Course)', 'https://www.youtube.com/watch?v=vLnPwxZdW4Y', 'Bro Code — Complete C++ beginner tutorial in one video', 'video', 1, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Introduction to C++ (learncpp.com)', 'https://www.learncpp.com/cpp-tutorial/introduction-to-cplusplus/', 'What is C++, history, and why learn it', 'article', 1, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Setting Up Your IDE', 'https://www.learncpp.com/cpp-tutorial/introduction-to-the-compiler-linker-and-libraries/', 'Compiler, linker, and IDE setup guide', 'article', 1, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Variables & Data Types', 'https://www.learncpp.com/cpp-tutorial/introduction-to-variables/', 'Variable declaration, initialization, and fundamental data types', 'article', 1, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Input & Output (cin/cout)', 'https://www.learncpp.com/cpp-tutorial/introduction-to-iostream-cout-cin-and-endl/', 'Using iostream for user input and output', 'article', 1, 5);

-- Week 2: Operators & Flow Control
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Operators in C++', 'https://www.youtube.com/watch?v=cZc-bSCSliU', 'Caleb Curry — Arithmetic, relational, logical operators', 'video', 2, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'If-else & Switch Statements', 'https://www.learncpp.com/cpp-tutorial/if-statements-and-blocks/', 'Conditional control flow with if-else and switch', 'article', 2, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Loops in C++ (for, while, do-while)', 'https://www.learncpp.com/cpp-tutorial/for-statements/', 'All loop types explained with examples', 'article', 2, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Break, Continue & Scope', 'https://www.learncpp.com/cpp-tutorial/break-and-continue/', 'Loop control statements and variable scope', 'article', 2, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Type Conversion & Casting', 'https://www.learncpp.com/cpp-tutorial/implicit-type-conversion-coercion/', 'Implicit and explicit type conversions in C++', 'article', 2, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Bitwise Operators', 'https://www.learncpp.com/cpp-tutorial/bitwise-operators/', 'AND, OR, XOR, NOT, shift operators explained', 'article', 2, 6);

-- Week 3: Pointers, Arrays & Data Types
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Pointers in C++', 'https://www.youtube.com/watch?v=DTxHyVn0ODg', 'The Cherno — Understanding pointers clearly', 'video', 3, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'References in C++', 'https://www.youtube.com/watch?v=IzoFn3dfsPA', 'The Cherno — References vs pointers', 'video', 3, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Arrays in C++', 'https://www.youtube.com/watch?v=ENDaJi08jCU', 'The Cherno — Static and dynamic arrays', 'video', 3, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Strings in C++', 'https://www.youtube.com/watch?v=ijIxcB9qjaU', 'The Cherno — C-style strings vs std::string', 'video', 3, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Structs in C++', 'https://www.learncpp.com/cpp-tutorial/introduction-to-structs-members-and-member-selection/', 'User-defined data types with structs', 'article', 3, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Enums in C++', 'https://www.youtube.com/watch?v=x55jfOd5PEE', 'The Cherno — Enumerations and scoped enums', 'video', 3, 6);

-- Week 4: Functions & Recursion
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Functions in C++', 'https://www.youtube.com/watch?v=V9zuox47zr0', 'The Cherno — Function declaration, definition, and calling', 'video', 4, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Function Parameters (Pass by Value/Reference)', 'https://www.learncpp.com/cpp-tutorial/passing-arguments-by-value/', 'Pass by value, reference, and pointer', 'article', 4, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Default Arguments & Overloading', 'https://www.learncpp.com/cpp-tutorial/default-arguments/', 'Default parameters and function overloading', 'article', 4, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Recursion', 'https://www.learncpp.com/cpp-tutorial/recursion/', 'Recursive functions, base cases, factorial, fibonacci', 'article', 4, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Header Files & Multi-file Projects', 'https://www.youtube.com/watch?v=9RJTQmK0YPI', 'The Cherno — Header files, include guards, and linking', 'video', 4, 5);

-- Week 5: Revise & Practice
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Basic Problems', 'https://www.geeksforgeeks.org/cpp-programming-examples/', 'GFG — Even/Odd, Sum of Digits, Reverse Number', 'exercise', 5, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Logic Building', 'https://www.hackerrank.com/domains/cpp', 'HackerRank — C++ domain problems', 'exercise', 5, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ Practice: Arrays & Strings', 'https://leetcode.com/problemset/?topicSlugs=array,string', 'LeetCode — Array and string problems', 'exercise', 5, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ Exercises (W3Schools)', 'https://www.w3schools.com/cpp/cpp_exercises.asp', 'W3Schools — Interactive C++ exercises by topic', 'exercise', 5, 4);

-- Week 6: OOP Part 1
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Classes & Objects', 'https://www.youtube.com/watch?v=2BP8NhxjrO0', 'The Cherno — Classes in C++', 'video', 6, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Classes vs Structs', 'https://www.youtube.com/watch?v=fLgTtaqqJp0', 'The Cherno — When to use class vs struct', 'video', 6, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Constructors & Destructors', 'https://www.youtube.com/watch?v=FXhALMsHwEY', 'The Cherno — Constructor types and destructor', 'video', 6, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Encapsulation & Access Specifiers', 'https://www.learncpp.com/cpp-tutorial/access-specifiers-and-encapsulation/', 'Public, private, protected access modifiers', 'article', 6, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Static Members & Methods', 'https://www.youtube.com/watch?v=V-BFlMrBtqQ', 'The Cherno — Static keyword in classes', 'video', 6, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'The ''this'' Pointer', 'https://www.learncpp.com/cpp-tutorial/the-hidden-this-pointer-and-member-function-chaining/', 'The implicit this pointer and its uses', 'article', 6, 6);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Const in Classes', 'https://www.youtube.com/watch?v=4fJBrditnJU', 'The Cherno — Const correctness with classes', 'video', 6, 7);

-- Week 7: OOP Part 2
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Copy Constructor & Copy Assignment', 'https://www.learncpp.com/cpp-tutorial/the-copy-constructor/', 'Deep copy vs shallow copy, Rule of Three', 'article', 7, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Operator Overloading', 'https://www.youtube.com/watch?v=mS9755gF66w', 'The Cherno — Overloading operators in C++', 'video', 7, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Dynamic Memory (new/delete)', 'https://www.youtube.com/watch?v=sNcj0lPxFfc', 'The Cherno — Heap allocation with new and delete', 'video', 7, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Smart Pointers', 'https://www.youtube.com/watch?v=UOB7-B2MfwA', 'The Cherno — unique_ptr, shared_ptr, weak_ptr', 'video', 7, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Move Semantics & Rvalue References', 'https://www.youtube.com/watch?v=ehMg6zvXuMY', 'The Cherno — Move semantics explained', 'video', 7, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Shallow vs Deep Copy', 'https://www.geeksforgeeks.org/shallow-copy-and-deep-copy-in-c/', 'GFG — Difference between shallow and deep copy', 'article', 7, 6);

-- Week 8: OOP Part 3 — Inheritance & Polymorphism
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Inheritance', 'https://www.youtube.com/watch?v=X8nYM8wdNRE', 'The Cherno — Inheritance in C++', 'video', 8, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Types of Inheritance', 'https://www.learncpp.com/cpp-tutorial/introduction-to-inheritance/', 'Single, multiple, multilevel inheritance', 'article', 8, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Virtual Functions', 'https://www.youtube.com/watch?v=oIV2KchSyGQ', 'The Cherno — Virtual functions & vtables', 'video', 8, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Pure Virtual Functions (Interfaces)', 'https://www.youtube.com/watch?v=UWAdd13EfM8', 'The Cherno — Abstract classes and interfaces', 'video', 8, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Virtual Destructors', 'https://www.youtube.com/watch?v=jELbKhGkEi0', 'The Cherno — Why virtual destructors matter', 'video', 8, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Multiple Inheritance & Diamond Problem', 'https://www.learncpp.com/cpp-tutorial/virtual-base-classes/', 'Virtual base classes and the diamond problem', 'article', 8, 6);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Casting in C++ (static, dynamic, const, reinterpret)', 'https://www.youtube.com/watch?v=pWZS1MtxI-A', 'The Cherno — All four C++ casts explained', 'video', 8, 7);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'OOP Practice Problems', 'https://www.geeksforgeeks.org/cpp-polymorphism/', 'GFG — Practice polymorphism and inheritance', 'exercise', 8, 8);

-- Week 9: STL & Advanced Topics
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Templates in C++', 'https://www.youtube.com/watch?v=I-hZkUa9mIs', 'The Cherno — Function and class templates', 'video', 9, 1);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'std::vector', 'https://www.youtube.com/watch?v=PocJ5jXv8No', 'The Cherno — Using vectors properly', 'video', 9, 2);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'std::map & std::unordered_map', 'https://www.learncpp.com/cpp-tutorial/stdmap-and-stdmultimap/', 'Key-value containers: map, unordered_map', 'article', 9, 3);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Iterators', 'https://www.learncpp.com/cpp-tutorial/introduction-to-iterators/', 'Iterator types and how to traverse containers', 'article', 9, 4);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'Lambda Functions', 'https://www.youtube.com/watch?v=mWgmBBz0y8c', 'The Cherno — Lambda expressions in C++', 'video', 9, 5);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'STL Algorithms (sort, find, accumulate)', 'https://www.learncpp.com/cpp-tutorial/introduction-to-standard-library-algorithms/', 'Common STL algorithms and how to use them', 'article', 9, 6);
INSERT INTO public.resources (domain, category, title, url, description, type, week_number, order_in_week) VALUES ('cpp-programming', 'cpp-programming', 'C++ STL Cheat Sheet', 'https://www.geeksforgeeks.org/cpp-stl-cheat-sheet/', 'GFG — Quick reference for all STL containers and algorithms', 'docs', 9, 7);
